### PR TITLE
Added Theme to mantine components

### PR DESCRIPTION
**Pull request by miguel-merlin**
## Description
Added mantime provider. Added custom fields available in the Figma. Meeting with @sahanaali later to define custom props to components.

### CODE REVIEW

**Review by j-ferber — DISMISSED** [review]
Looks good. Just a general question: Do you know why it needs the hex value like 10 times?

**Comment by miguel-merlin** [comment]
> Looks good. Just a general question: Do you know why it needs the hex value like 10 times?

Yeah, you can configure the shades of the colors, that's why you need 10 colors in the array

**Comment by j-ferber** [comment]
Ahh ok, makes sense. Good to merge whenever your ready.

**Comment by miguel-merlin** [comment]
> Ahh ok, makes sense. Good to merge whenever your ready.

I'll just wait until after I meet with Sahana

**Comment by miguel-merlin** [comment]
@j-ferber This is ready to be merged. For some reason, I am getting this error in one of the components you created
```
 ⨯ TypeError: Cannot read properties of null (reading 'page')
    at RenderedPage (./src/app/[filename]/components.client.tsx:20:24)
  28 |  return (
  29 |          <div className='flex min-h-screen items-start justify-center gap-4 md:p-10 p-5 flex-col'>
> 30 |                  {data.page && <Blocks {...data.page} />}
     |                       ^
  31 |          </div>
  32 |  )
  33 | }
``` 
Do you know what the issue could be?

**Comment by j-ferber** [comment]
That's weird, it hasn't been a problem before. Not sure what it could be. Usually that error only comes up when a route is entered that doesn't exist in the pages under the content directory.

**Comment by ShawnAviles** [comment]
Can that not be fixed with just using 
` {data && data.page && <Blocks {...data.page} />}` or ` {data?.page && <Blocks {...data.page} />}`

**Comment by j-ferber** [comment]
I fixed it in the supporters block PR, tried updating the branch but didn't seem to work here. Can you see the error?

**Comment by miguel-merlin** [comment]
@j-ferber Thanks for solving the issue, do you know what it was?

**Comment by j-ferber** [comment]
Whenever a page was requested that didn't exist, it would throw an error which I didn't have proper handling for. So I just added a not found page and rendered that when the page wasn't found.

**Review by j-ferber — APPROVED** [review]
👍 LGTM

**Pull request merged**
