### PR TITLE
Added in the supporters page

### PR DESCRIPTION
**Pull request by snehabanda30**
Added in the supporters page. THe images can be added in.

### CODE REVIEW

**Comment by ShawnAviles** [comment]
In the future, pls attach photos of your changes. Helps with reviewing your PR

**Comment by Lucasha11** [comment]
[Link To Page](http://localhost:3000/our-supporters)

**Comment by ShawnAviles** [comment]
Whole bunch of merge conflicts need to be addressed, from your branch try `git rebase origin main`

**Review by ShawnAviles — CHANGES_REQUESTED** [review]
Whole bunch of merge conflicts need to be addressed, from your branch try git rebase origin main

**Comment by Lucasha11** [comment]
"head" commit should've fixed the merge conflicts on the "our-supporters" page

**Review by j-ferber — APPROVED** [review]
These look good, idk why hero is edited here tho

**Review by ShawnAviles — APPROVED** [review]

**Pull request merged**
