### PR TITLE
Added About Us pages

### PR DESCRIPTION
**Pull request by snehabanda30**
Added the About us page

### CODE REVIEW

**Review by j-ferber — CHANGES_REQUESTED** [review]
Can you replace the image under the header to use the banner/hero component instead of the carousel component? The carousel at the top of this page takes up too much space as I think its min height is the height of the screen.

**Comment by Lucasha11** [comment]
Changes: 
Title Image Grid -> Rich Text
Screenshot 2024-12-16 at 6 06 13 PM

Populate Tabs in team Gallery
Screenshot 2024-12-16 at 6 06 42 PM
Screenshot 2024-12-16 at 6 07 00 PM

Added Footer

**Comment by Lucasha11** [comment]
I totally screwed my push. Most of the changes can be reverted to the commits before today

**Comment by Lucasha11** [comment]
[Link to Page](http://localhost:3000/about-us)

**Review by j-ferber — APPROVED** [review]

**Pull request merged**
