### PR TITLE
our-impact page

### PR DESCRIPTION
**Pull request by johanngg7**
done. take a look and lmk if i need to change anything

### CODE REVIEW

**Review by j-ferber — CHANGES_REQUESTED** [review]
Can you group up the rich text components more? A lot of your rich-text elements are just individual use cases, which is adding a lot of extra space.

For example: 
image

You have each of these in the image as separate rich text components, however, you can combine them into one and use the "Heading 1" option rich text provides in combination with the colored text for the top part and normal text for the bottom.

**Comment by ShawnAviles** [comment]
@SevenThanh pls fix merge conflicts

**Comment by Lucasha11** [comment]
Added gradient over hero:
Screenshot 2024-12-17 at 4 02 09 PM

Reformatted Rich Text:
Screenshot 2024-12-17 at 4 02 26 PM

Added Images in Two Column:
Screenshot 2024-12-17 at 4 02 49 PM

Added Images and Rich Text
Screenshot 2024-12-17 at 4 03 04 PM

Added Two Column:
Screenshot 2024-12-17 at 4 03 24 PM

Added Two Column:
Screenshot 2024-12-17 at 4 03 34 PM

Added Testimonial Carousel:
Screenshot 2024-12-17 at 4 03 42 PM

**Comment by Lucasha11** [comment]
[Link to Page](http://localhost:3000/our-impact)

**Comment by j-ferber** [comment]
I think we can close this PR as the one I just merged has this our impact page on it

**Pull request closed without merging**
