### PR TITLE
Ghfmc done

### PR DESCRIPTION
**Pull request by johanngg7**
- let me know if there's anything I need to fix

### CODE REVIEW

**Comment by ShawnAviles** [comment]
@SevenThanh merge conflicts...

**Comment by Lucasha11** [comment]
Added BG color
Screenshot 2024-12-17 at 5 56 56 PM

Added Hero and Image Text Button
Screenshot 2024-12-17 at 5 57 08 PM

**Comment by Lucasha11** [comment]
[Link To Page](http://localhost:3000/how-to-find-resources-for-clients)

**Review by ShawnAviles — CHANGES_REQUESTED** [review]
You should rebase against main `git rebase main` from inside of your branch bc miguel's commits shouldn't be apart of your branch... @SevenThanh 

other than that just fix merge conflicts and you're good

**Review by ShawnAviles — APPROVED** [review]
Looks good, some components need more padding from the resource page but good to merge

**Pull request merged**
